// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcdKtUFXaI0a-TH_5p390fLKvrAdUC-3M',
    appId: '1:88152083064:web:fd5fdf621e5047f1fabb8d',
    messagingSenderId: '88152083064',
    projectId: 'relis-cb671',
    authDomain: 'relis-cb671.firebaseapp.com',
    storageBucket: 'relis-cb671.appspot.com',
    measurementId: 'G-2PNY06C040',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDhXk2jyL-klcndDQKw7wDmSInO9_3LHs',
    appId: '1:88152083064:android:6e0aa94f661afb0dfabb8d',
    messagingSenderId: '88152083064',
    projectId: 'relis-cb671',
    storageBucket: 'relis-cb671.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCplQwCsWrljJTKSxrObS2Jd3zlqirHLY',
    appId: '1:88152083064:ios:921f44f1faba86d4fabb8d',
    messagingSenderId: '88152083064',
    projectId: 'relis-cb671',
    storageBucket: 'relis-cb671.appspot.com',
    iosClientId: '88152083064-89pm7mei20nm9e7n8rqgfmbudpkccdqt.apps.googleusercontent.com',
    iosBundleId: 'com.example.relis',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCplQwCsWrljJTKSxrObS2Jd3zlqirHLY',
    appId: '1:88152083064:ios:e00cca6a982be756fabb8d',
    messagingSenderId: '88152083064',
    projectId: 'relis-cb671',
    storageBucket: 'relis-cb671.appspot.com',
    iosClientId: '88152083064-rkmqhuqto5e5aoeid6vlee8d9s7bf2jr.apps.googleusercontent.com',
    iosBundleId: 'com.example.relis.RunnerTests',
  );
}
